### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by ema07cqc** [DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur#1]
Hi there, thanks for this. Just tried on my EliteBook 840 G4 and its working!
Intel Core i7-7500
BIOS P78 Ver.01.16 03/29/2018

They are specific steps to make the Integrated Intel WiFi work? macOS Catalina 10.15.4 using your EFI folder.

Thanks again!!

**Comment by DominikHackintosh** [comment]
Hello!

for Installing at Catalina download the Catalina Airportitlwm and install it with Hackintool to /Library/Extension. After that reboot. You will find this option under menu Utilities. The tool you can download here: https://github.com/headkaze/Hackintool/releases/download/3.4.6/Hackintool.zip

Try it out and let me know!

Greetings from Hungary

**Comment by ema07cqc** [comment]
<img width="1280" alt="Screen Shot 2020-10-16 at 10 51 18" src="https://user-images.githubusercontent.com/56570026/96267186-e7e8ae00-0f9d-11eb-901f-03d0b0913623.png">
Well, this is magic!
Intel WiFi 5Ghz working!!!!!
Thank you!!!!!!!!!

**Comment by DominikHackintosh** [comment]
nice to see this, what exact Wifi Card you use?
