### ISSUE TITLE
Switching from Clover / Installation Instructions?

### ISSUE THREAD

**Issue by cyberfunk** [DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur#2]
Hi Dominik,
I'd like to make the switch to your setup with OpenCore but I'm not sure how to do a clean transition from my Clover setup. Is it possible to delete all traces of Clover setup and switch to this setup without doing a fresh install? Also can I keep my existing SMBIOS from my clover Config.plist and use it with OpenCore?

**Comment by DominikHackintosh** [comment]
hi Cyberfunk, 

1st you can keep your whole clover configuration and you can use opencore side by side.
2nd you can use your clover smbios data in my opcencore config plist, you just need to edit it
3rd you don´t need any fresh install
Greetings

**Comment by cyberfunk** [comment]
So you're saying all of the kexts installed to /Library/Extensions using Rehabmans guide for Clover have no affect when using OpenCore?

**Comment by DominikHackintosh** [comment]
i never ever installed any kexts to /Library/Extension, keep them in your clover kext folder. only for catalina i put airportitlwm to L/E, but this was the only exception.

**Comment by DominikHackintosh** [comment]
cyberfunk, i uploaded my old working clover configuration, there you can have a look for comparison, all needed kexts are inside efi folder. its definitely not up to date, because i don´t use clover anymore https://github.com/DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur/blob/master/CLOVER5119.zip

**Comment by cyberfunk** [comment]
Thanks! I wonder why Rehabman method uses both Clover folder AND /Library/Extensions for kexts?

**Comment by DominikHackintosh** [comment]
at these times, some kexts were not loadable  by clover, at the beginning i followed this guide, its quite good!  for me it did not install anything to L/E https://www.tonymacx86.com/threads/guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch.261719/

**Comment by cyberfunk** [comment]
This is my Library/Extensions folder  under a fresh install with Clover and Rehabman guide. The kexts with the grey tag are all those installed by Rehabman .sh scripts I use this guide: https://www.tonymacx86.com/threads/guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch.261719/

![Screen Shot 2020-10-25 at 7 42 45 AM](https://user-images.githubusercontent.com/12664589/97110339-ea31c300-1695-11eb-99f9-475c60470634.jpg)

**Comment by cyberfunk** [comment]
This is my Clover kexts folder under the same install.
![Screen Shot 2020-10-25 at 7 47 11 AM](https://user-images.githubusercontent.com/12664589/97110396-51e80e00-1696-11eb-8dd9-2c4e727ebd00.jpg)

**Comment by DominikHackintosh** [comment]
do the grey ones from L/E to your clover kext folder. before make a efi usb stick with my opencore efi so you have a backup and you should be able to boot

**Comment by cyberfunk** [comment]
I already have at least a couple backups so I can boot in emergencies. I always clone my main drive including EFI stricture and then I keep my original macOS installer USB with EFI updated as well. I just want a way to be completely rid of Clover which I think I may have to do a complete fresh install unless I can find uninstall instructions for Clover and Rehabman guide.

**Comment by DominikHackintosh** [comment]
then install big sur, i am only on big sur for a while

**Comment by cyberfunk** [comment]
So I cleaned out all clover remnants and dropped in your OC folder in my EFI. I updated smbios with my info and the computer will not boot. It shows the apple logo but no progress bar. It just freezes at the Apple logo. Did I miss a step?

**Comment by cyberfunk** [comment]
Never mind. I needed to clear my NVRAM. Thanks so much for this everything seems to be working smoothly!

**Comment by DominikHackintosh** [comment]
you are welcome!
