### ISSUE TITLE
Can't Boot with external monitor

### ISSUE THREAD

**Issue by cyberfunk** [DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur#3]
Hi Dominik. Everything was perfect when using my Laptop standalone with OpenCore. As soon as I moved back over to my desk and plugged in my external monitor it was game over. I can't boot with the external monitor attached. Do you have any idea why an external monitor breaks the OpenCore setup?

**Comment by DominikHackintosh** [comment]
oh sorry i have no ideas and i also can not test because i have no external monitor. i have to look at a friends place to try. maybe you could try to compare the graphics section from kreizles opencore config plist, i think they were different. greetings

**Comment by cyberfunk** [comment]
I just tried to boot with Kreizles EFI and have the same issue. The external graphics just aren't loading correctly and I get a black display. I'm out of my depth with all of this as all I've ever done is use Rehabmans script with Clover and that works all the way around. I like what you've done with the SD Card and Intel Wifi and I also like the higher security with OpenCore and SIP. Eventually I'd like to make the switch.

**Comment by DominikHackintosh** [comment]
how do you connect to your external monitor? VGA or the display port? you could try to use graphics patches from your clover config for opencore. sorry but like i wrote, i have no external monitor here to check and find a solution

**Comment by cyberfunk** [comment]
Thanks! I should be the one apologizing for my ignorance in these matters. I'll try to figure out what and where graphics patches are and how to transfer them😁

**Comment by cyberfunk** [comment]
Hello again. Can you tell me how to get BlueTooth and WiFi working? I installed this card:

Intel 8260NGW Dual Band WiFi 802.11ac 1Gps + Bluetooth, M.2, NGFF Lenovo 00JT530

But nothing works. I can see BlueTooth activated but it won't connect to my device. The Wifi icon is dimmed out and I cannot connect. I've reset and cleaned NVRAM.

**Comment by DominikHackintosh** [comment]
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha, do the propper kexts to your opencore efi folder, if you work with clover install it to /L/E

**Comment by DominikHackintosh** [comment]
![Screenshot 2020-10-28 at 00 03 04](https://user-images.githubusercontent.com/71799198/97371280-1f662d00-18b1-11eb-9742-221a269d1884.png)
![Screenshot 2020-10-28 at 00 03 17](https://user-images.githubusercontent.com/71799198/97371285-21c88700-18b1-11eb-928e-b85fb050403d.png)

**Comment by cyberfunk** [comment]
Oh man what a disaster. I switched over to Clover to see if the kexts worked over there and it bricked my whole setup. My system would not boot at all with those two kexts installed to Library/Extensions. I could not even boot in safe mode to get rid of them.  I had to boot from an external backup drive and go in and delete those kexts by hand. I'm not giving up hope but I think the devs on this new Intel WiFi tweak need to iron out a few bugs before this works for everybody.

**Comment by cyberfunk** [comment]
Well I guess it helps if you read the instructions. I was placing BOTH files in /Library/Extensions whihc the instructions state you should NEVER do. I put release 1.1.0 of AirportItlwm.kext in both Clover EFI kext folder AND /Library/Extensions and voila! Everything seems to be working fine. Thanks again for your patience and insights.

**Comment by cyberfunk** [comment]
I don't know why I closed this since my original graphics issue is still a work in progress.🤦‍♂️ Anyway I would love to try to help in getting your package working with external monitors and display port. Can you tell me how you came to construct your pcroot section of the config.plist? Did you use a code generator of some kind where you pug in values and it spits out a config or was it all done by hand?

**Comment by cyberfunk** [comment]
HAHA! YESSSSSS! Alright my friend get your external monitor ready! So I ransacked Rehabman's config.plist for 840 G4 and Clover and found the necessary pciroot patches. I added them to your config.plist and sure enough my external monitor is up and running. If you'd like to modify your setup just add this extra set of entries to your config.plist So you'll have three pciroot groups in total where there were just two before.

![Screen](https://user-images.githubusercontent.com/12664589/97524605-50526a80-1962-11eb-9a87-03ff7ba465a5.jpg)

**Comment by cyberfunk** [comment]
Thanks again for all for the work you've put into this project!

**Comment by DominikHackintosh** [comment]
Hi my friend, this are very good news, i will add them to my config and make my github completely new without any zipped file, so that changes are much easier. So i have something for you, i was able with help to get new bios versions working. That is really great. just add this patch to your config: https://github.com/kecinzer/hpelitebook850g5-opencore/commit/65338feaa5d3cd005f8ba19ecc5250816d44d776

**Comment by DominikHackintosh** [comment]
can you please tell me how you connected to your external monitor?

**Comment by cyberfunk** [comment]
UPDATE! Hi Dominik. Please hold off on adding my patches. I took a closer look at my monitor and realized I'm not getting the correct high Dpi resolutions on my 4K monitor. Everything is slightly blurry so I still have work to do.I will send another update when I have ironed out these issues.

**Comment by cyberfunk** [comment]
Btw thanks for the BIOS update. I will take a look at that once this monitor issue is sorted. I'm connecting via the Display port.

**Comment by DominikHackintosh** [comment]
ok fine so far, i completely reworked my github Repository, now changes are very easy to do. i added your monitor solution so far and also the BIOS Update Solution, you can have a closer look there ;)

**Comment by cyberfunk** [comment]
Alright so I think I may have a solution. Get rid of the two patches that you had in your original config.plist and ONLY keep the new patch from Rehabman that I added in the red brackets of the image I sent you earlier. I have no idea how and why this works but with just using Rehabman pciroot patch I can boot and both internal display and external monitor work perfectly with High DPI crisp 4K and other scaling options on the external 4K monitor. 

The only issue I see is that when you boot with laptop closed and external monitor attached and THEN you try to open the laptop the display is black and cannot be seen again unless you reboot with the laptop open. Please let me know your experience using ONLY Rehabman pciroot patch and deleting the two other patches.

**Comment by DominikHackintosh** [comment]
https://www.olarila.com/topic/6420-guide-mobile-intel-hd-graphics-clover-or-opencore/?fbclid=IwAR3S_OPZW5JqBmyJihS8E98xjhYSod3lesM5fYxO-Nkx_C4IV3Q7MU9328g

**Comment by DominikHackintosh** [comment]
okay at the moment i am looking for a solution for lid control, maybe you also could make tests, i want that when i  close the lid it falls to sleep and when opening waking up. at the moment it doesnt do anything when closing the lid, but sleep so far works very good for me.....

**Comment by cyberfunk** [comment]
For me both internal and external monitors sleep/turn off properly. When you say sleep do you mean hybernate for your system? Or are you saying when you shut your lid the display stays on?

**Comment by DominikHackintosh** [comment]
i mean hibernation, also when i close lide the backlight stays on. there must be a solution for it ;) step by step. did you try new bios?

**Comment by cyberfunk** [comment]
> https://www.olarila.com/topic/6420-guide-mobile-intel-hd-graphics-clover-or-opencore/?fbclid=IwAR3S_OPZW5JqBmyJihS8E98xjhYSod3lesM5fYxO-Nkx_C4IV3Q7MU9328g

What is this patch supposed to do? Also I noticed you did not delete this patch from your config:

<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
			<dict>
				<key>layout-id</key>
				<integer>15</integer>
			</dict>

In my config the ONLY patch I have is Rehabmans patch so maybe that's why you're having issues? Try deleting EVERYTHING except the Rehabman patch and let me know if you have issues with the display going to sleep on lid close. Also if you can tell me what that patch you linked does I may try it out.

**Comment by DominikHackintosh** [comment]
i think it came from tests with card reader, ok i delete it but i let the olarila patch, also tried with rehabman patch we will see i have to test with external monitor. i have a new pnfl. aml in my repository, with the print button now you can switch of trackpad, was missing before. try to make bios update to 1.35 works great, for clover and opencore...

**Comment by cyberfunk** [comment]
Oh OK well I don't want to break your Card Reader so make sure that still works as well before you delete any of your own patches:-) So you're saying that patched you linked to is to get the new BIOS working?

**Comment by DominikHackintosh** [comment]
oh man, you won´t believe what was wrong. i made tests with windows and linux, same problem, so i looked for the hardware. There is a missing magnet in the lid, how crazy!!!!!

**Comment by cyberfunk** [comment]
WOW! That's incredible. I'm glad you found the issue.

**Comment by cyberfunk** [comment]
So just to be clear that patch you're telling me to add is ONLY to allow a BIOS update?

**Comment by DominikHackintosh** [comment]
this allows you to use all bios versions, because at 1.31 it stopped working for mac os, i was successfull, found a very tiny neodyme and was glueing it into the lid. how crazy!!!
[VID_20201029_211223.mp4.zip](https://github.com/DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur/files/5461021/VID_20201029_211223.mp4.zip)

**Comment by cyberfunk** [comment]
OMG I'm such a goof. The patches you're telling me to add to allow BIOS are the same ones that I'm telling you to REMOVE to get external monitor working properly.🤣 I can't use that BIOS patch because it breaks external monitor resolutions. I can only get low resolutions with that patch installed which looks terrible on a 4K monitor. Everything is blurry without proper High DPi resolutions. Once you attach a 4K monitor you will see what I'm talking about.

**Comment by DominikHackintosh** [comment]
what methode you used? you can add patch to your config there also you can add this dsdt to your acpi, just add it to acpi section in your config 
[SSDT-SET-STAS.aml.zip](https://github.com/DominikHackintosh/HP-EliteBook-840-G4-Hackintosh-Big-Sur/files/5461251/SSDT-SET-STAS.aml.zip)

**Comment by cyberfunk** [comment]
What method did I use for what?

**Comment by DominikHackintosh** [comment]
there are two ways: 1 with the patch in your config and the better way adding the ssdt-set-stas.aml to your acpi folder. please try this!

**Comment by DominikHackintosh** [comment]
i think you are a little bit confused, ok the first picture is the config patch, this is the not so good solution, the better solution is with ssdt table (2nd Picture)
![Screenshot 2020-10-29 at 22 07 51](https://user-images.githubusercontent.com/71799198/97632844-667c2b80-1a33-11eb-9937-57d754f1db6f.png)
![Screenshot 2020-10-29 at 22 08 20](https://user-images.githubusercontent.com/71799198/97632869-6e3bd000-1a33-11eb-887d-b07d5dbedde9.png)

**Comment by cyberfunk** [comment]
It worked!!! Thanks so much for that! I used method number two.😁

**Comment by DominikHackintosh** [comment]
Great! nice to hear, so now we should be so far that everything is working, okay for me there is on tiny thing, after sleep the cardreader makes some problems. but so far its ok!

**Comment by DominikHackintosh** [comment]
my new magnet for the lid 
![IMG_20201029_211046](https://user-images.githubusercontent.com/71799198/97635325-73028300-1a37-11eb-9738-ea3d95f34960.jpg)
came from a pack of cigarrete -papers pack,  they have small neodym magnets for closing lol
![IMG_20201029_211031](https://user-images.githubusercontent.com/71799198/97635308-6c740b80-1a37-11eb-8aa3-affa26b9348d.jpg)

**Comment by cyberfunk** [comment]
Oh wow! That's cool. I just realized you have an i5 processor! I thought we had the same computer. I have the i7 model!

**Comment by DominikHackintosh** [comment]
if you like we can work together on our project

**Comment by cyberfunk** [comment]
I'll leave it to the experts. All of this is way beyond my pay grade. I can hack a solution here or there but at the end of the day it's just a hack and if there are serious issues I would not want to be responsible for wrecking someones setup. I appreciate the offer and thanks again for providing all of the packages and data for this OpenCore install.

**Comment by cyberfunk** [comment]
How has your experience with Big Sur been? Did you upgrade or fresh install? I just tried to upgrade and it bricked my setup so I had to restore back to Catalina.

**Comment by DominikHackintosh** [comment]
hey sorry did not see that you answered, no i installed it side by side to catalina, means i have 2 mac os partitions

**Comment by cyberfunk** [comment]
OK. Yeah I tried to do a direct upgrade and it was disastrous. I think an upgrade install is not possible from a hackintosh just yet.🤣

**Comment by DominikHackintosh** [comment]
yeah make free space or install a 2nd sata ssd, there i installed catalina, big sur is on the first partition of my big nvme. works very well, most time i boot up big sur, next week it will be final released ;)

**Comment by cyberfunk** [comment]
I just tried to upgrade using the official release 11.0.1 but same result. It locks up at first boot and goes no further. Can you tell me what I am missing. Is there some big change I need to make to the OpenCore EFI or config.plist so I can upgrade. Why won't a direct upgrade work? I don't have a spare drive to do a fresh install.

**Comment by DominikHackintosh** [comment]
hi i downloaded the full image from appstore, flashed it to stick and booted straight into the installer, without any problem. Deleted my old BS Partition and installed it straight. it felt like out of the box, had nothing to do and everything worked fine!

**Comment by cyberfunk** [comment]
Maybe I have a wrong setting in my config.plist or EFI. I'm using your config.plist just updated with my SMBIOS and those tweaks I made to the graphics. When  I download the full installer and do an upgrade install from within Catalina it just won't compete the process. Once everything is finished and it goes to reboot it freezes at about 90% progress bar under the apple and the fans continue to ramp up but it will not finish booting. If I boot from a backup external drive the drive with Big Sur on it will not mount but a partition called "Update" does mount from that drive. Have you tried to do an upgrade install?

**Comment by DominikHackintosh** [comment]
i generally don´t upgrade, in installed big sur beta then made every new
beta update. now on date of release i was downloading the full 12GB image
from appstore, flashed it to a stick. booted up and formatted my whole big
sur bet partition and installed it to there. it worked like a charme. yes
under catalina you only will see update partition of big sur, thats normal

Am Sa., 14. Nov. 2020 um 17:09 Uhr schrieb Cyberfunk <
notifications@github.com>:

**Comment by DominikHackintosh** [comment]
you could try completely download my efi and try to boot your big sur
stick, i would recommend this step

Am Sa., 14. Nov. 2020 um 18:05 Uhr schrieb Dominik Rosenthal <
thefreak1980@googlemail.com>:

**Comment by cyberfunk** [comment]
Ahh I see! So it's like back in the day when you could not see APFS partitions from Yosemite? I still don't understand why it won't boot though. I guess I'll have to figure out how to do a fresh install. Thanks so much for your input!

**Comment by DominikHackintosh** [comment]
try this tool from chris, this helps you to flash the stick from your bs image. but juist let it copy, skip the last step of efi creating. you won´t need this, use your efi

**Comment by cyberfunk** [comment]
Thanks!

**Comment by cyberfunk** [comment]
So I flashed Big Sur to my USB using creatinstall method wiped my main drive and installed Big Sur and it still won't boot. I transferred over my EFI to both the USB and main drive and while the installer will boot the main drive will not. At first I got the chinese screen saying your computer needs to be restarted. Next it would almost boot then crash and restart. Now I disabled SIP and tried to boot and it goes to about 90% and no further with fans spinning at top speed. Back to Catalina...🤦🏼‍♂️

**Comment by cyberfunk** [comment]
OMG!!!!! I DID IT! I want to thank you from the deepest place in my heart for all of your work on this. I wish you would have told me that there are HUGE differences between your release and the folders at the center top of the repo page. That was the issue. I was using your old EFI on the right hand side where releases usually are and that is what was bricking my system. It looks like you did massive updates to your EFI in the folders at the center top of the repo. Once I implemented all of the changes you made to config.plist and kext files I was able to do an upgrade install without even using a USB stick. Thanks again! Maybe you should get rid of that old release on the right so others won't make the same mistake I did.🤣

**Comment by DominikHackintosh** [comment]
ok nice to hear i was wondering why it did not work Congratulations ;)
